sonar.organization=vannadii
sonar.projectKey=vannadii_devplat
sonar.sources=crates,docs/site/src
sonar.tests=crates
sonar.test.inclusions=crates/**/tests/**/*.rs
sonar.rust.lcov.reportPaths=target/lcov.info
sonar.exclusions=target/**,docs/site/book/**,crates/*/schemas/*.schema.json,deploy/**,docker/**,.ironloom/**
sonar.coverage.exclusions=crates/**/tests/**/*.rs
