sonar.organization=vannadii
sonar.projectKey=vannadii_ironloom
sonar.projectName=Ironloom
sonar.sources=crates,site/guide-docs
sonar.tests=crates
sonar.test.inclusions=crates/**/tests/**/*.rs
sonar.rust.lcov.reportPaths=target/lcov.info
sonar.exclusions=target/**,site/guide-docs/.vitepress/dist/**,crates/*/schemas/*.schema.json,deploy/**,docker/**,.ironloom/**
sonar.coverage.exclusions=crates/**/tests/**/*.rs
