apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ironloom.fullname" . }}-state
  labels:
    {{- include "ironloom.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
