import { describe, expect, it } from 'vitest';

import {
  DEVPLAT_ACTION_AUTOFIX,
  DEVPLAT_ACTION_CLEANUP_ARTIFACTS,
  DEVPLAT_ACTION_DELETE_WORKTREE,
  DEVPLAT_ACTION_DESTRUCTIVE_CLEANUP,
  DEVPLAT_ACTION_EXECUTE_COMMAND,
  DEVPLAT_ACTION_MERGE_NOW,
  DEVPLAT_ACTION_MERGE_PR,
  DEVPLAT_ACTION_PUBLISH,
  DEVPLAT_ACTION_PUBLISH_RELEASE,
  DEVPLAT_ACTION_REBASE_ALL_DEPENDENTS,
  DEVPLAT_ACTION_REBASE_DEPENDENTS,
  DEVPLAT_ACTION_RELEASE_WORKTREE,
  DEVPLAT_ACTION_RETRY_GATES,
  DEVPLAT_ACTION_RUN_COMMAND,
  DEVPLAT_ACTION_RUN_GATES,
  DEVPLAT_ACTION_SYNC_WORKTREE,
  DEVPLAT_ACTION_UPDATE_SPEC,
} from '@vannadii/devplat-core';
import {
  POLICY_AUTOFIX_ACTIONS,
  POLICY_ACTION_CATEGORY_AUTOFIX,
  POLICY_ACTION_CATEGORY_COMMAND_EXECUTION,
  POLICY_ACTION_CATEGORY_DESTRUCTIVE_CLEANUP,
  POLICY_ACTION_CATEGORY_MERGE,
  POLICY_ACTION_CATEGORY_PUBLISH,
  POLICY_ACTION_CATEGORY_REBASE,
  POLICY_ACTION_CATEGORY_ROUTINE,
  POLICY_ACTION_CATEGORY_WORKTREE_RELEASE,
  POLICY_COMMAND_EXECUTION_ACTIONS,
  POLICY_DESTRUCTIVE_ACTIONS,
  POLICY_DESTRUCTIVE_CLEANUP_ACTIONS,
  POLICY_EXTERNAL_PUBLISH_ACTIONS,
  POLICY_MERGE_ACTIONS,
  POLICY_REBASE_ACTIONS,
  POLICY_SENSITIVE_ACTIONS,
} from './constants.js';

describe('decision-policy constants', () => {
  const cases = [
    {
      name: 'exports policy action sets from a constants module',
      inputs: {},
      mock: () => ({}),
      assert: () => {
        expect(POLICY_SENSITIVE_ACTIONS).toContain(DEVPLAT_ACTION_MERGE_NOW);
        expect(POLICY_SENSITIVE_ACTIONS).toContain(
          DEVPLAT_ACTION_REBASE_ALL_DEPENDENTS,
        );
        expect(POLICY_SENSITIVE_ACTIONS).toContain(
          DEVPLAT_ACTION_SYNC_WORKTREE,
        );
        expect(POLICY_SENSITIVE_ACTIONS).toContain(
          DEVPLAT_ACTION_RELEASE_WORKTREE,
        );
        expect(POLICY_SENSITIVE_ACTIONS).toContain(DEVPLAT_ACTION_UPDATE_SPEC);
        expect(POLICY_DESTRUCTIVE_ACTIONS).toEqual([
          DEVPLAT_ACTION_RELEASE_WORKTREE,
        ]);
        expect(POLICY_EXTERNAL_PUBLISH_ACTIONS).toEqual([
          DEVPLAT_ACTION_PUBLISH,
          DEVPLAT_ACTION_PUBLISH_RELEASE,
        ]);
        expect(POLICY_MERGE_ACTIONS).toEqual([
          DEVPLAT_ACTION_MERGE_NOW,
          DEVPLAT_ACTION_MERGE_PR,
        ]);
        expect(POLICY_COMMAND_EXECUTION_ACTIONS).toEqual([
          DEVPLAT_ACTION_EXECUTE_COMMAND,
          DEVPLAT_ACTION_RUN_COMMAND,
          DEVPLAT_ACTION_RUN_GATES,
          DEVPLAT_ACTION_RETRY_GATES,
        ]);
        expect(POLICY_REBASE_ACTIONS).toEqual([
          DEVPLAT_ACTION_REBASE_DEPENDENTS,
          DEVPLAT_ACTION_REBASE_ALL_DEPENDENTS,
        ]);
        expect(POLICY_AUTOFIX_ACTIONS).toContain(DEVPLAT_ACTION_AUTOFIX);
        expect(POLICY_DESTRUCTIVE_CLEANUP_ACTIONS).toEqual([
          DEVPLAT_ACTION_DESTRUCTIVE_CLEANUP,
          DEVPLAT_ACTION_DELETE_WORKTREE,
          DEVPLAT_ACTION_CLEANUP_ARTIFACTS,
        ]);
        expect(POLICY_ACTION_CATEGORY_MERGE).toBe('merge');
        expect(POLICY_ACTION_CATEGORY_COMMAND_EXECUTION).toBe(
          'command-execution',
        );
        expect(POLICY_ACTION_CATEGORY_WORKTREE_RELEASE).toBe(
          'worktree-release',
        );
        expect(POLICY_ACTION_CATEGORY_REBASE).toBe('rebase');
        expect(POLICY_ACTION_CATEGORY_PUBLISH).toBe(DEVPLAT_ACTION_PUBLISH);
        expect(POLICY_ACTION_CATEGORY_AUTOFIX).toBe(DEVPLAT_ACTION_AUTOFIX);
        expect(POLICY_ACTION_CATEGORY_DESTRUCTIVE_CLEANUP).toBe(
          DEVPLAT_ACTION_DESTRUCTIVE_CLEANUP,
        );
        expect(POLICY_ACTION_CATEGORY_ROUTINE).toBe('routine');
      },
    },
  ];

  it.each(cases)('$name', (testCase) => {
    expect.hasAssertions();
    const context = testCase.mock();

    testCase.assert(context, testCase.inputs);
  });
});
